name: Build macOS .app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app

      - name: Build app with py2app
        run: |
          rm -rf build dist
          python setup.py py2app

      - name: Show dist
        run: ls -la dist || true

      - name: Package artifact
        run: |
          mkdir -p artifact
          cp -R dist/*.app artifact/ || true
          if [ -d "artifact" ]; then
            cd artifact
            zip -r "../silaigo_app_${{ matrix.os }}.zip" ./*.app || true
            cd ..
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: silaigo_app_${{ matrix.os }}
          path: silaigo_app_${{ matrix.os }}.zip