name: Build macOS .app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python framework (Tkinter compatible)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: x64
          check-latest: true

      # 3️⃣ Upgrade pip and install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Install py2app
      - name: Install py2app
        run: pip install py2app

      # 5️⃣ Build the .app
      - name: Build .app
        run: |
          python setup.py py2app

      # 6️⃣ Upload the .app artifact
      - name: Upload macOS .app
        uses: actions/upload-artifact@v4
        with:
          name: invoice-generator-app
          path: dist